server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: non_null
